export const LOAD_API_GAMES = 'LOAD_API_GAMES';
export const ADD_VIDEOGAME = 'ADD_VIDEOGAME';
export const FIND_BY_NAME = 'FIND_BY_NAME';
export const FIND_BY_ID = 'FIND_BY_ID';
export const GET_GENRES = 'GET_GENRES';
export const SORT_BY_NAME = 'SORT_BY_NAME';
export const SORT_BY_RATING = 'SORT_BY_RATING';
export const CLEAR_SEARCH_BY_NAME = 'CLEAR_SEARCH_BY_NAME';
export const CLEAR_SEARCH_BY_ID = 'CLEAR_SEARCH_BY_ID';
export const FILTER_VIDEOGAME_BY_GENRE = 'FILTER_VIDEOGAME_BY_GENRE';
export const FILTER_VIDEOGAME_BY_CREATION = 'FILTER_VIDEOGAME_BY_CREATION';
export const FILTER_VIDEOGAME_BY_RATING = 'FILTER_VIDEOGAME_BY_RATING';
//!===============TO BE USE IN THE CRUD======================
export const EDIT_VIDEOGAME = 'EDIT_VIDEOGAME';
export const DELETE_VIDEOGAME = 'DELETE_VIDEOGAME';
